<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kalender Kegiatan OSIS</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="kalender.css">
</head>
<body>
    <!-- Header Section -->
    <header>
        <div class="container header-container">
            <div class="logo-container">
                <img src="foto/logo-sekolah.png" alt="Logo Sekolah" class="logo">
                <img src="foto/logo-osis.png" alt="Logo OSIS" class="logo">
            </div>
            
            <div class="datetime-container">
                <div id="current-datetime"></div>
            </div>
            <nav class="desktop-nav">
                <a href="index.php">Beranda</a>
                <a href="struktur.php">Struktur OSIS</a>
                <a href="kalender.php">Kalender Kegiatan</a>
                <a href="news.php">Berita & Pengumuman</a>
            </nav>
            <button class="mobile-menu-btn" id="mobileMenuBtn">☰</button>
        </div>
    </header>

    <!-- Sidebar Navigation -->
    <div class="sidebar" id="sidebar">
        <button class="close-sidebar" id="closeSidebar">&times;</button>
        <a href="index.html">Beranda</a>
        <a href="struktur.html">Struktur OSIS</a>
        <a href="kalender.html">Kalender Kegiatan</a>
        <a href="news.html">Berita & Pengumuman</a>
        <a href="galeri.html">Galeri Kegiatan</a>
        <a href="formulir.html">Formulir</a>
        <a href="kontak.html">Kontak</a>
    </div>

    <!-- Main Content -->
    <main class="container calendar-container">
        <section class="calendar-section">
            <h1>Kalender Kegiatan OSIS</h1>
            
            <div class="calendar-grid">
                <!-- Calendar Card -->
                <div class="calendar-card">
                    <div class="calendar-header">
                        <h2 id="current-month-year">November 2023</h2>
                        <div class="calendar-nav">
                            <button id="prev-month"><i class="fas fa-chevron-left"></i></button>
                            <button id="next-month"><i class="fas fa-chevron-right"></i></button>
                        </div>
                    </div>
                    <table class="calendar-table" id="calendar-table">
                        <!-- Calendar will be generated by JavaScript -->
                    </table>
                </div>
                
                <!-- Events Card -->
                <div class="events-card">
                    <h2>Kegiatan Mendatang</h2>
                    <ul class="events-list" id="events-list">
                        <!-- Events will be populated by JavaScript -->
                    </ul>
                </div>
            </div>
        </section>
        
        <!-- Stats Section -->
        <section class="stats-section">
            <h2 class="section-title">Statistik Kegiatan</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-icon">
                        <i class="fas fa-calendar-check"></i>
                    </div>
                    <div class="stat-content">
                        <h3>Kegiatan Bulan Ini</h3>
                        <div class="stat-number">5</div>
                        <p>Kegiatan terjadwal</p>
                    </div>
                </div>
                
                <div class="stat-card">
                    <div class="stat-icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <div class="stat-content">
                        <h3>Partisipasi Siswa</h3>
                        <div class="stat-number">85%</div>
                        <p>Rata-rata kehadiran</p>
                    </div>
                </div>
                
                <div class="stat-card">
                    <div class="stat-icon">
                        <i class="fas fa-trophy"></i>
                    </div>
                    <div class="stat-content">
                        <h3>Prestasi</h3>
                        <div class="stat-number">12</div>
                        <p>Penghargaan tahun ini</p>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <!-- Event Modal -->
    <div class="modal" id="event-modal">
        <div class="modal-content">
            <span class="close-modal">&times;</span>
            <h2 id="modal-title">Judul Kegiatan</h2>
            <div class="modal-body">
                <div class="modal-info">
                    <p><i class="fas fa-calendar-day"></i> <span id="modal-date">Tanggal</span></p>
                    <p><i class="fas fa-clock"></i> <span id="modal-time">Waktu</span></p>
                    <p><i class="fas fa-map-marker-alt"></i> <span id="modal-location">Lokasi</span></p>
                    <p><i class="fas fa-user-tie"></i> <span id="modal-person">Penanggung Jawab</span></p>
                </div>
                <div class="modal-description">
                    <h3>Deskripsi Kegiatan</h3>
                    <p id="modal-description">Deskripsi kegiatan akan muncul di sini.</p>
                    
                    <h3>Persiapan yang Diperlukan</h3>
                    <ul id="modal-preparations">
                        <!-- Will be populated by JavaScript -->
                    </ul>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn reminder-btn"><i class="fas fa-bell"></i> Atur Pengingat</button>
                <button class="btn share-btn"><i class="fas fa-share-alt"></i> Bagikan</button>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container footer-container">
            <div class="footer-section">
                <h3>Tentang OSIS</h3>
                <p>Organisasi Siswa Intra Sekolah (OSIS) merupakan organisasi resmi sekolah yang bertujuan untuk mengembangkan potensi siswa dan menyalurkan aspirasi siwa.</p>
            </div>
            
           
            
            <div class="footer-section">
                <h3>Kontak Kami</h3>
                <div class="contact-info">
                    <div class="contact-item">
                        <i class="fas fa-map-marker-alt"></i>
                        <span>Jl. Gajah Mada N0. 20 Medan, Sumatera Utara, Indonesia</span>
                    </div>
                    <div class="contact-item">
                        <i class="fas fa-envelope"></i>
                        <span>osisraksana@.sch.id</span>
                    </div>
                    <div class="contact-item">
                        <i class="fas fa-phone"></i>
                        <span></span>
                    </div>
                </div>
            </div>
            
            <div class="footer-section">
                <h3>Sosial Media</h3>
                <div class="social-media">
                    <a href="https://www.instagram.com/osisraksanamdn/" class="social-icon"><i class="fab fa-instagram"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="social-icon"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="container">
                <p>&copy; 2025 OSIS Yayasan Pendidikan Raksana Semua hak dilindungi.</p>
            </div>
        </div>
    </footer>

    <script src="kalender.js"></script>
</body>
</html>